Update prepare-development-environment.md
kubesphere/dev-guide pull request #83
Opened 2022-08-19 11:31 UTC by patrickluoyu

Signed-off-by: patrickluoyu <patrickluo@yunify.com>

Please take a look. Thanks!

/assign @rayzhou2017 @benjaminhuo

2022-08-19 11:46 UTC, rayzhou2017 commented on sites/extension-dev-guide/content/zh/get-started/_index.md
> +欢迎来到 KubeSphere 插件开发快速入门，本节将帮助您快速搭建插件开发环境并了解 KubeSphere 插件开发的基本原理。
不是说“插件”统一改成“扩展组件”吗？

2022-08-19 11:49 UTC, rayzhou2017 commented on sites/extension-dev-guide/content/zh/get-started/prepare-development-environment.md
> +* kubesphere：最小化模式的 KubeSphere 平台，仅包含 KubeSphere 的基本组件，用于为扩展组件提供 API 服务。kubesphere 容器可以运行在本地主机上，也可以运行在远程主机上以避免本地主机资源占用过高。
kubesphere --》KubeSphere

2022-08-19 11:51 UTC, rayzhou2017 commented on sites/extension-dev-guide/content/zh/get-started/prepare-development-environment.md
> +* 为避免兼容性问题，建议采用 Linux 主机作为开发主机。
这个不能这么建议，很多开发者日常用的是windows，Mac，linux反而不多。通常情况开发者会用vs code这类IDE开发。Linux可以作为快速体验的环境。

2022-08-19 11:52 UTC, rayzhou2017 commented on sites/extension-dev-guide/content/zh/get-started/prepare-development-environment.md
> +### 安装最小化 KubeSphere
4.0应该不存在最小化ks的说法了，应该是ks core了

2022-08-20 05:23 UTC, benjaminhuo requested changes

2022-08-20 05:23 UTC, benjaminhuo commented on sites/extension-dev-guide/content/zh/get-started/hello-world-extension.md
> +1. 执行以下命令在本地在开始之前我们需要创建一个本地文件目录用作数据持久化，用来保存项目文件。
```suggestion
1. 在开始之前我们需要创建一个本地文件目录用来保存项目文件。
```

2022-08-20 12:09 UTC, patrickluoyu commented on sites/extension-dev-guide/content/zh/get-started/prepare-development-environment.md
> +* kubesphere：最小化模式的 KubeSphere 平台，仅包含 KubeSphere 的基本组件，用于为扩展组件提供 API 服务。kubesphere 容器可以运行在本地主机上，也可以运行在远程主机上以避免本地主机资源占用过高。
那个容器的名称确实是 kubesphere，后面执行 docker 命令的时候命令里面也是写 kubesphere

2022-08-20 12:23 UTC, patrickluoyu commented on sites/extension-dev-guide/content/zh/get-started/prepare-development-environment.md
> +* kubesphere：最小化模式的 KubeSphere 平台，仅包含 KubeSphere 的基本组件，用于为扩展组件提供 API 服务。kubesphere 容器可以运行在本地主机上，也可以运行在远程主机上以避免本地主机资源占用过高。
写容器的名称是为了让开发者明白这套环境搭建流程其实就是创建了两个容器

2022-08-20 12:25 UTC, patrickluoyu commented on sites/extension-dev-guide/content/zh/get-started/hello-world-extension.md
> +1. 执行以下命令在本地在开始之前我们需要创建一个本地文件目录用作数据持久化，用来保存项目文件。
我先把这句话改了，hello-world-extension.md 这个文档还要继续改

2022-08-20 12:41 UTC, rayzhou2017 commented on sites/extension-dev-guide/content/zh/get-started/prepare-development-environment.md
> +* kubesphere：最小化模式的 KubeSphere 平台，仅包含 KubeSphere 的基本组件，用于为扩展组件提供 API 服务。kubesphere 容器可以运行在本地主机上，也可以运行在远程主机上以避免本地主机资源占用过高。
ok

2022-08-20 13:58 UTC, merged